-- Add suggestion/feedback storage for WhatsApp bot.

ALTER TABLE wa_users
ADD COLUMN IF NOT EXISTS active_suggestion_id bigint;

CREATE TABLE IF NOT EXISTS wa_suggestions (
  id bigint generated by default as identity primary key,
  wa_id text not null,
  suggestion_text text not null,
  contact_opt_in boolean,
  contact_phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS wa_suggestions_wa_id_idx
ON wa_suggestions (wa_id);
